#!/usr/bin/env bash
# scripts/build.sh
# Builds .mdc files for all skills (or a single skill if passed as argument).
# Also generates Claude Code plugin manifests (.claude-plugin/) from SKILL.md frontmatter.
#
# Usage:
#   ./scripts/build.sh               # build all skills
#   ./scripts/build.sh k8s-operator  # build one skill
#
# Output:
#   cursor-rules/<name>.mdc                       (Cursor rule file)
#   skills/<name>/.claude-plugin/plugin.json       (Claude Code plugin manifest)
#   .claude-plugin/marketplace.json                (Claude Code marketplace catalog)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SKILLS_DIR="$REPO_ROOT/skills"
DIST_DIR="$REPO_ROOT/cursor-rules"
MARKETPLACE_JSON="$REPO_ROOT/.claude-plugin/marketplace.json"

# ── helpers ────────────────────────────────────────────────────────────────────

log()  { echo "▶ $*"; }
ok()   { echo "✓ $*"; }
err()  { echo "✗ $*" >&2; exit 1; }

# Extract a YAML frontmatter field from SKILL.md (handles folded/block scalars)
# Joins continuation lines with spaces for folded (>) or newlines for literal (|).
# Usage: extract_field <field> <file>
extract_field() {
  local field="$1" file="$2"
  awk "
    /^---/{ if(p) exit; p=1; next }
    p && /^${field}:/{
      sub(/^${field}:[[:space:]]*/,\"\")
      folded = sub(/^>[[:space:]]*/,\"\")
      if(length(\$0)>0){ print; exit }
      result = \"\"
      while((getline line)>0){
        if(line ~ /^[[:space:]]+/){
          sub(/^[[:space:]]*/,\"\",line)
          if(result != \"\") result = result \" \"
          result = result line
        } else break
      }
      print result
      exit
    }
  " "$file" | tr -d '\"'
}

# Escape a string for safe JSON embedding
json_escape() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g; s/\t/\\t/g'
}

# Build a single skill directory into a .mdc file + .claude-plugin/plugin.json
build_skill() {
  local skill_dir="$1"
  local name
  name="$(basename "$skill_dir")"
  local skill_md="$skill_dir/SKILL.md"
  local refs_dir="$skill_dir/references"
  local out_file="$DIST_DIR/${name}.mdc"

  log "Building $name ..."

  [[ -f "$skill_md" ]] || err "Missing SKILL.md in $skill_dir"

  # Extract description from SKILL.md frontmatter
  local description
  description="$(extract_field description "$skill_md")"
  [[ -n "$description" ]] || err "$name: could not extract 'description' from SKILL.md frontmatter"

  # ── write .mdc (Cursor rule) ───────────────────────────────────────────────
  {
    printf -- "---\n"
    printf "description: %s\n" "$description"
    printf "globs:\n"

    local globs_raw
    globs_raw="$(awk '/^---/{if(p)exit; p=1; next} p && /^globs:/,/^[^ ]/' "$skill_md" \
      | grep '^\s*-' || true)"

    if [[ -n "$globs_raw" ]]; then
      echo "$globs_raw"
    else
      printf '  - "**/*.go"\n'
      printf '  - "**/*.yaml"\n'
    fi

    printf "alwaysApply: false\n"
    printf -- "---\n\n"

    awk '/^---/{if(p)exit; p=1; next} p' "$skill_md"

    if [[ -d "$refs_dir" ]]; then
      for ref in "$refs_dir"/*.md; do
        [[ -f "$ref" ]] || continue
        printf "\n\n---\n\n"
        cat "$ref"
      done
    fi
  } > "$out_file"

  ok "$name → cursor-rules/${name}.mdc"

  # ── write .claude-plugin/plugin.json (Claude Code plugin manifest) ─────────
  local plugin_dir="$skill_dir/.claude-plugin"
  mkdir -p "$plugin_dir"

  local desc_escaped
  desc_escaped="$(json_escape "$description")"

  local version
  version="$(extract_field version "$skill_md")"
  version="${version:-1.0.0}"

  cat > "$plugin_dir/plugin.json" <<EOF
{
  "//": "AUTO-GENERATED by scripts/build.sh — do not edit manually. Source: SKILL.md",
  "name": "${name}",
  "description": "${desc_escaped}",
  "version": "${version}",
  "author": {
    "name": "zarcen"
  },
  "homepage": "https://github.com/zarcen/ai-persona/tree/main/skills/${name}"
}
EOF

  ok "$name → skills/${name}/.claude-plugin/plugin.json"
}

# Regenerate .claude-plugin/marketplace.json from all skill directories.
# Merges into the existing file so manually-added fields are preserved.
build_marketplace() {
  log "Generating marketplace.json ..."

  mkdir -p "$(dirname "$MARKETPLACE_JSON")"

  # Collect skill names and descriptions into a temp file (tab-separated)
  local tmpfile
  tmpfile="$(mktemp)"

  for skill_dir in "$SKILLS_DIR"/*/; do
    [[ -d "$skill_dir" ]] || continue
    local name
    name="$(basename "$skill_dir")"
    local skill_md="$skill_dir/SKILL.md"
    [[ -f "$skill_md" ]] || continue

    local description version
    description="$(extract_field description "$skill_md")"
    version="$(extract_field version "$skill_md")"
    version="${version:-1.0.0}"
    printf '%s\t%s\t%s\n' "$name" "$version" "$description" >> "$tmpfile"
  done

  local count
  count="$(python3 - "$MARKETPLACE_JSON" "$tmpfile" <<'PYEOF'
import json, sys, os

marketplace_path = sys.argv[1]
data_file = sys.argv[2]

generated = {}
with open(data_file) as f:
    for line in f:
        line = line.rstrip("\n")
        parts = line.split("\t")
        if len(parts) < 3:
            continue
        name, version, desc = parts[0], parts[1], parts[2]
        generated[name] = {"description": desc, "version": version}

comment = "AUTO-GENERATED by scripts/build.sh — description, version, and plugins list are managed by the build. Other fields may be edited manually."

if os.path.exists(marketplace_path):
    with open(marketplace_path) as f:
        marketplace = json.load(f)
else:
    marketplace = {
        "name": "ai-persona",
        "owner": {"name": "zarcen"},
        "metadata": {"description": "Reusable agent skills for AI coding agents"},
        "plugins": []
    }

marketplace = {"//": comment, **{k: v for k, v in marketplace.items() if k != "//"}}

existing_by_name = {}
for plugin in marketplace.get("plugins", []):
    existing_by_name[plugin["name"]] = plugin

new_plugins = []
for name in sorted(generated):
    gen = generated[name]
    if name in existing_by_name:
        entry = existing_by_name[name]
        entry["description"] = gen["description"]
        entry["version"] = gen["version"]
        new_plugins.append(entry)
    else:
        new_plugins.append({
            "name": name,
            "source": "./skills/" + name,
            "description": gen["description"],
            "version": gen["version"]
        })

marketplace["plugins"] = new_plugins

with open(marketplace_path, "w") as f:
    json.dump(marketplace, f, indent=2, ensure_ascii=False)
    f.write("\n")

print(len(new_plugins))
PYEOF
)"

  rm -f "$tmpfile"
  ok "marketplace.json (${count} plugin(s))"
}

# ── main ───────────────────────────────────────────────────────────────────────

mkdir -p "$DIST_DIR"

if [[ $# -eq 1 ]]; then
  skill_dir="$SKILLS_DIR/$1"
  [[ -d "$skill_dir" ]] || err "Skill '$1' not found in $SKILLS_DIR"
  build_skill "$skill_dir"
  build_marketplace
else
  found=0
  for skill_dir in "$SKILLS_DIR"/*/; do
    [[ -d "$skill_dir" ]] || continue
    build_skill "$skill_dir"
    found=$((found + 1))
  done
  [[ $found -gt 0 ]] || err "No skill directories found in $SKILLS_DIR"
  build_marketplace
  log "Built $found skill(s)."
fi
